server:
  servlet:
    context-path: /api
  port: 8080

logging:
  level:
    org:
      mybatis: DEBUG
    org.springframework.security: DEBUG

spring:
  application:
    name: coding-platform
  main:
    banner-mode: OFF
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coding-platform?useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  data:
    redis:
      host: 192.168.1.203
      port: 6379
      timeout: 30s # 客户端连接超时处理
      jedis:
        pool:
          max-idle: 8  # 连接池中的最大空闲连接
          max-active: 8 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负数表示无限

mybatis:
  type-aliases-package: cn.caigh.coding_platform.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


## Custom configuration
env: DEV

tencent:
  captchaAppid: 194520119
  appSecretKey: DUhOXWubHcgMIk4UvApAFjHb8